before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: FLWtd8fEI+1xvCqaDkqhD4hI9rnn7a6pSWpXXXBhQpEzqIoE/b3hnopFx+h4kl81IeqzB5JwU/XzrYBuD7mcsLdqK4KI74HzvlUZlECtZDdLAeMuJu62vHKbO5sNO54WAsrMsjKSslV3iWYyB0RLh1F3gcnJeViExxHaX6USRWJhJMBSs1xzyjl7paJZEpI2Pjj8rqZlb9SK4VeYWY+/l6xCzFmBBNkcmkVr8vdI5dGDCFcyFT+//lCuAMORYGkFOolwzK2knBktbzp5AVErC6uFMuORLlaoZOZg+dB2XdCA3X69sH4WmGou+iBzLGCyrcoXu9SkhiKVD5zNTGGWPMOoQ87S2C4hdA0WNap3V0HoYnFvDzYg1s0TLuuu1hZk+92r2OIYDpUF9ozp/iad5WxFjAzhzR34cHnAAWCAjI6qHjpkiCCA6husLXDxOMZvTkwiDdP6SngP1LrRkO3Qxo6aIiF29H46zlhGUWrFzgbLyIHsezFp3WkZGg4izja81ONs+/rZ69FOk45FLxEw/lA87/8oDJGUrikNt6Tsz9uBrVUo/a3fUGG4nsXUfxEBqdlK5uyDyGzbhzKU1tcsQEhHkJwCHJYC0qkX14qrYJEx0moQpnZQj471l5YU3r4wRQj8xf5lqPFd9LuFGBcP1DlS/gDECRWIMw7lN/bb2es= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
